name: flutter_tv_master
description: Flutter TV Master Configuration.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.0.0
  bloc: ^8.1.1
  pinput: ^2.2.30
  wakelock: ^0.6.2
  flutter_bloc: ^8.1.2
  auto_animated: ^3.1.0
  dpad_container: ^2.0.3
  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.5
  flutter_animator: ^3.2.2
  responsive_framework: ^0.2.0
  flutter_secure_storage: ^8.0.0
  flutter_feather_icons: ^2.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/image/
    - assets/lottie/
    - assets/vector/

  fonts:
    - family: Outfit
      fonts:
        - asset: assets/font/outfit/Outfit-Black.ttf
        - asset: assets/font/outfit/Outfit-Bold.ttf
        - asset: assets/font/outfit/Outfit-ExtraBold.ttf
        - asset: assets/font/outfit/Outfit-ExtraLight.ttf
        - asset: assets/font/outfit/Outfit-Light.ttf
        - asset: assets/font/outfit/Outfit-Medium.ttf
        - asset: assets/font/outfit/Outfit-Regular.ttf
        - asset: assets/font/outfit/Outfit-SemiBold.ttf
        - asset: assets/font/outfit/Outfit-Thin.ttf